### ISSUE TITLE
Error when adding search from URL

### ISSUE THREAD

**Issue by neilio** [deanishe/alfred-searchio#62]
First of all, thanks for developing this!

Running the latest version of Alfred on macOS 11.2.

I'm running into an error when I try to add a search from a URL. When I select "Import Search…" I get the following error:

```
[10:19:32.821] ERROR: Searchio![Script Filter] Code 1: .
10:19:32 workflow.py:2055 DEBUG    ---------- Searchio! (2.0.1) ----------
10:19:32 workflow.py:1462 DEBUG    reading settings from /Users/neilio/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-searchio/settings.json
10:19:32 workflow.py:2339 DEBUG    update check not due
10:19:32 cli.py:63 DEBUG    args={'--help': False,
 '--version': False,
 '<args>': [''],
 '<command>': 'web'}
execution error: Error: Error: Application can't be found. (-2700)
10:19:32 workflow.py:2074 ERROR    Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', '\nfunction run(argv) {\n    var apps = {};\n    argv.forEach(function(name) {\n        if (Application(name).running()) {\n            apps[name] = true;\n        } else {\n            apps[name] = false;\n        }\n    });\n    return JSON.stringify(apps);\n}\n', 'Google Chrome', 'Safari']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/neilio/Dropbox (Personal)/Library/Sync/Alfred.alfredpreferences/workflows/user.workflow.9D757FD2-1084-4B5C-849A-A23115C48CCD/lib/workflow/workflow.py", line 2067, in run
	func(self)
  File "/Users/neilio/Dropbox (Personal)/Library/Sync/Alfred.alfredpreferences/workflows/user.workflow.9D757FD2-1084-4B5C-849A-A23115C48CCD/lib/searchio/cli.py", line 127, in cli
	return run(wf, argv)
  File "/Users/neilio/Dropbox (Personal)/Library/Sync/Alfred.alfredpreferences/workflows/user.workflow.9D757FD2-1084-4B5C-849A-A23115C48CCD/lib/searchio/cmd/web.py", line 212, in run
	return do_get_url(wf, args)
  File "/Users/neilio/Dropbox (Personal)/Library/Sync/Alfred.alfredpreferences/workflows/user.workflow.9D757FD2-1084-4B5C-849A-A23115C48CCD/lib/searchio/cmd/web.py", line 122, in do_get_url
	output = subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
	raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', '\nfunction run(argv) {\n    var apps = {};\n    argv.forEach(function(name) {\n        if (Application(name).running()) {\n            apps[name] = true;\n        } else {\n            apps[name] = false;\n        }\n    });\n    return JSON.stringify(apps);\n}\n', 'Google Chrome', 'Safari']' returned non-zero exit status 1
10:19:32 workflow.py:2076 INFO     for assistance, see: https://github.com/deanishe/alfred-searchio/issues
10:19:32 workflow.py:2097 DEBUG    ---------- finished in 0.051s ----------
[10:19:32.823] Searchio![Script Filter] {"items": [{"valid": false, "subtitle": "Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', '\\nfunction run(argv) {\\n    var apps = {};\\n    argv.forEach(function(name) {\\n        if (Application(name).running()) {\\n            apps[name] = true;\\n        } else {\\n            apps[name] = false;\\n        }\\n    });\\n    return JSON.stringify(apps);\\n}\\n', 'Google Chrome', 'Safari']' returned non-zero exit status 1", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'Searchio!'"}]}
```

**Comment by pkumath** [comment]
Have the same problem.
