### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by rzolin** [deanishe/alfred-searchio#66]
Hey. Just installed the workflow and when I try to search "g <anything>" I get the error:

Error in workflow 'Serchio!"
too many values to unpack

I am on Big Sur OS

Here is the debug output:

[13:53:58.506] Logging Started...
[13:54:03.469] Searchio![Script Filter] Queuing argument 't'
[13:54:03.800] Searchio![Script Filter] Script with argv '(null)' finished
[13:54:03.803] ERROR: Searchio![Script Filter] Code 1: .
13:54:03 workflow.py:2061 DEBUG    ---------- Searchio! (1.8.1) ----------
13:54:03 workflow.py:1468 DEBUG    reading settings from /Users/rzolin/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-searchio/settings.json
13:54:03 workflow.py:2343 DEBUG    update check not due
13:54:03 search.py:585 DEBUG    subclass : Yandex.ru
13:54:03 search.py:585 DEBUG    subclass : Naver.com
13:54:03 search.py:585 DEBUG    subclass : Google
13:54:03 search.py:585 DEBUG    subclass : Google Images
13:54:03 search.py:585 DEBUG    subclass : Google Maps
13:54:03 search.py:585 DEBUG    subclass : YouTube
13:54:03 search.py:585 DEBUG    subclass : Amazon
13:54:03 search.py:585 DEBUG    subclass : eBay
13:54:03 search.py:585 DEBUG    subclass : Bing
13:54:03 search.py:585 DEBUG    subclass : Yahoo!
13:54:03 search.py:585 DEBUG    subclass : DuckDuckGo
13:54:03 search.py:585 DEBUG    subclass : Wiktionary
13:54:03 search.py:585 DEBUG    subclass : Wikipedia
13:54:03 search.py:585 DEBUG    subclass : Wikia
13:54:03 search.py:585 DEBUG    subclass : Ask
13:54:03 workflow.py:1695 DEBUG    loading cached data: /Users/rzolin/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-searchio/__workflow_latest_version.cpickle
13:54:03 workflow.py:1695 DEBUG    loading cached data: /Users/rzolin/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-searchio/default-language.cpickle
13:54:03 search.py:195 DEBUG    key components : [u'Google', u'lang', u'en', u'query', u't', u'engine', u'google']
13:54:03 workflow.py:2080 ERROR    too many values to unpack
Traceback (most recent call last):
  File "/Users/rzolin/Documents/Alfred.alfredpreferences/workflows/user.workflow.461E7E8C-5DE1-442F-AA6E-FFC8F5676784/workflow/workflow.py", line 2073, in run
    func(self)
  File "search.py", line 688, in main
    results = engine.search()
  File "search.py", line 200, in search
    results = self.wf.cached_data(key, self._suggest, max_age=600)
  File "/Users/rzolin/Documents/Alfred.alfredpreferences/workflows/user.workflow.461E7E8C-5DE1-442F-AA6E-FFC8F5676784/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "search.py", line 273, in _suggest
    _, results = response.json()
ValueError: too many values to unpack
13:54:03 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/alfred-searchio/issues
13:54:03 workflow.py:2103 DEBUG    ---------- finished in 0.124s ----------
[13:54:03.809] Searchio![Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Searchio!'</title><subtitle>too many values to unpack</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[13:56:15.785] Searchio![Script Filter] Queuing argument 't'
[13:56:16.059] Searchio![Script Filter] Script with argv '(null)' finished
[13:56:16.061] ERROR: Searchio![Script Filter] Code 1: .
13:56:15 workflow.py:2061 DEBUG    ---------- Searchio! (1.8.1) ----------
13:56:15 workflow.py:1468 DEBUG    reading settings from /Users/rzolin/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-searchio/settings.json
13:56:15 workflow.py:2343 DEBUG    update check not due
13:56:15 search.py:585 DEBUG    subclass : Yandex.ru
13:56:15 search.py:585 DEBUG    subclass : Naver.com
13:56:15 search.py:585 DEBUG    subclass : Google
13:56:15 search.py:585 DEBUG    subclass : Google Images
13:56:15 search.py:585 DEBUG    subclass : Google Maps
13:56:15 search.py:585 DEBUG    subclass : YouTube
13:56:15 search.py:585 DEBUG    subclass : Amazon
13:56:15 search.py:585 DEBUG    subclass : eBay
13:56:15 search.py:585 DEBUG    subclass : Bing
13:56:15 search.py:585 DEBUG    subclass : Yahoo!
13:56:15 search.py:585 DEBUG    subclass : DuckDuckGo
13:56:15 search.py:585 DEBUG    subclass : Wiktionary
13:56:15 search.py:585 DEBUG    subclass : Wikipedia
13:56:15 search.py:585 DEBUG    subclass : Wikia
13:56:15 search.py:585 DEBUG    subclass : Ask
13:56:15 workflow.py:1695 DEBUG    loading cached data: /Users/rzolin/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-searchio/__workflow_latest_version.cpickle
13:56:15 workflow.py:1695 DEBUG    loading cached data: /Users/rzolin/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-searchio/default-language.cpickle
13:56:15 search.py:195 DEBUG    key components : [u'Google', u'lang', u'en', u'query', u't', u'engine', u'google']
13:56:16 workflow.py:2080 ERROR    too many values to unpack
Traceback (most recent call last):
  File "/Users/rzolin/Documents/Alfred.alfredpreferences/workflows/user.workflow.461E7E8C-5DE1-442F-AA6E-FFC8F5676784/workflow/workflow.py", line 2073, in run
    func(self)
  File "search.py", line 688, in main
    results = engine.search()
  File "search.py", line 200, in search
    results = self.wf.cached_data(key, self._suggest, max_age=600)
  File "/Users/rzolin/Documents/Alfred.alfredpreferences/workflows/user.workflow.461E7E8C-5DE1-442F-AA6E-FFC8F5676784/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "search.py", line 273, in _suggest
    _, results = response.json()
ValueError: too many values to unpack
13:56:16 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/alfred-searchio/issues
13:56:16 workflow.py:2103 DEBUG    ---------- finished in 0.104s ----------
[13:56:16.067] Searchio![Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Searchio!'</title><subtitle>too many values to unpack</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by brank87** [comment]
Having the same issue.
