### ISSUE TITLE
Wiki Search Error

### ISSUE THREAD

**Issue by mikedvzo** [deanishe/alfred-searchio#7]
alfred-searchio returns an error when searching Wikipedia as of today.  Here is the debug

[2016-10-13 12:28:42][ERROR: input.scriptfilter] Code 1: 12:28:42 workflow.py:1972 DEBUG    Workflow version : 1.8.1
12:28:42 workflow.py:1387 DEBUG    Reading settings from `/Users/mdivince/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-searchio/settings.json` ...
12:28:42 workflow.py:2233 DEBUG    Update check not due
12:28:42 search.py:585 DEBUG    subclass : Yandex.ru
12:28:42 search.py:585 DEBUG    subclass : Naver.com
12:28:42 search.py:585 DEBUG    subclass : Google
12:28:42 search.py:585 DEBUG    subclass : Google Images
12:28:42 search.py:585 DEBUG    subclass : Google Maps
12:28:42 search.py:585 DEBUG    subclass : YouTube
12:28:42 search.py:585 DEBUG    subclass : Amazon
12:28:42 search.py:585 DEBUG    subclass : eBay
12:28:42 search.py:585 DEBUG    subclass : Bing
12:28:42 search.py:585 DEBUG    subclass : Yahoo!
12:28:42 search.py:585 DEBUG    subclass : DuckDuckGo
12:28:42 search.py:585 DEBUG    subclass : Wiktionary
12:28:42 search.py:585 DEBUG    subclass : Wikipedia
12:28:42 search.py:585 DEBUG    subclass : Wikia
12:28:42 search.py:585 DEBUG    subclass : Ask
12:28:42 workflow.py:1610 DEBUG    Loading cached data from : /Users/mdivince/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-searchio/**workflow_update_status.cpickle
12:28:42 workflow.py:2181 DEBUG    update_data : {u'available': False}
12:28:42 workflow.py:1610 DEBUG    Loading cached data from : /Users/mdivince/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-searchio/default-language.cpickle
12:28:42 search.py:195 DEBUG    key components : [u'Wikipedia', u'lang', u'en', u'query', u'dal', u'engine', u'wikipedia']
12:28:42 workflow.py:1990 ERROR    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Traceback (most recent call last):
  File "/Users/mdivince/Dropbox/Sync/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7BC80B5F-83F8-4CB2-9672-B27FB49564E5/workflow/workflow.py", line 1983, in run
    func(self)
  File "search.py", line 688, in main
    results = engine.search()
  File "search.py", line 200, in search
    results = self.wf.cached_data(key, self._suggest, max_age=600)
  File "/Users/mdivince/Dropbox/Sync/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7BC80B5F-83F8-4CB2-9672-B27FB49564E5/workflow/workflow.py", line 1616, in cached_data
    data = data_func()
  File "search.py", line 529, in _suggest
    'search': self.options['query']})
  File "/Users/mdivince/Dropbox/Sync/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7BC80B5F-83F8-4CB2-9672-B27FB49564E5/workflow/web.py", line 540, in get
    auth=auth, timeout=timeout, allow_redirects=allow_redirects)
  File "/Users/mdivince/Dropbox/Sync/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7BC80B5F-83F8-4CB2-9672-B27FB49564E5/workflow/web.py", line 528, in request
    return Response(req)
  File "/Users/mdivince/Dropbox/Sync/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7BC80B5F-83F8-4CB2-9672-B27FB49564E5/workflow/web.py", line 211, in __init**
    self.raw = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
12:28:42 workflow.py:1993 INFO     For assistance, see: https://github.com/deanishe/alfred-searchio/issues
12:28:42 workflow.py:2008 DEBUG    Workflow finished in 0.192 seconds.

**Comment by deanishe** [comment]
Network problem
